spring:
  application:
    name: jda-spring-template

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/jda-template}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

bot:
  token: ${BOT_TOKEN:your-token-here}